### ISSUE TITLE
Support More Postgres Settings

### ISSUE THREAD

**Issue by markbeme** [eventide-project/message-store-postgres#28]
Hello, and thank you for your hard work on such a great open source offering.

My project sets `sslmode` to `verify-ca`; therefore, I also need `sslrootcert`.

In addition, because my database is configured for mutual TLS authentication, I need `sslcert` and `sslkey` as well.  While I don't currently use `sslpassword`, others may.

Please consider supporting not just these connection-critical `pg` gem settings, but potentially some others.

For handy reference, here's the code I'm asking about:

https://github.com/eventide-project/message-store-postgres/blob/master/lib/message_store/postgres/settings.rb
https://github.com/eventide-project/message-store-postgres/blob/c05e88cb332500f2fa91c3882a33d8896f76a74a/settings/message_store_postgres.json

Note that the `pg` gem doesn't actually document what it supports.  Instead, it supports everything as a pass through from a Ruby Hash to libpq.

You would think that libpq and the Postgres documentation would be in sync, but... here's the doc:

https://www.postgresql.org/docs/current/libpq-envars.html

... but the code actually supports more things, like `sslpassword`, for example!

https://github.com/postgres/postgres/blob/29836df323d752d534deb7b922cd48f08132e044/src/interfaces/libpq/fe-connect.c#L189C1-L189C1

Consider carefully, and remember, I appreciate you.

**Comment by sbellware** [comment]
Done.

See: http://docs.eventide-project.org/user-guide/settings.html#settings-attributes
